[build]
  environment = { NODE_ENV = "production", NODE_OPTIONS = "--experimental-modules" }

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "mongoose",
    "cors",
    "express-mongo-sanitize",
    "dotenv",
    "serverless-http"
  ]

# Catch-all redirect for API calls
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
